int16 AUTO_MODE_ON = 1         # 开启自动模式
int16 AUTO_MODE_OFF = 2        # 关闭自动模式
int16 MOVEMENT_START = 3       # 开始运动
int16 MOVEMENT_STOP = 4        # 停止运动
int16 ENABLE_CLEAN_HOLE1 = 5   # 使能1号炉口清渣
int16 DISABLE_CLEAN_HOLE1 = 6  # 禁用1号炉口清渣
int16 ENABLE_CLEAN_HOLE2 = 7   # 使能2号炉口清渣
int16 DISABLE_CLEAN_HOLE2 = 8  # 禁用2号炉口清渣
int16 SYSETM_RESET = 9         # 系统复位
int16 SAFETY_BACK = 10         # 安全撤回
int16 AUTO_MODE_START_MOVE = 11   # 自动模式开始运动
int16 CONTINUE_RUN = 12        # 解除外部停止，并开始继续运行
int16 cmd